theme: jekyll-theme-hacker

paginate: 10
plugins: [jekyll-paginate]
paginate_path: "blog/:num/"

title: DefCon Holland
description: DefCon groups DC3115 and DC3120

timezone: Europe/Amsterdam
future: true
encoding: utf-8

permalink: pretty
markdown: kramdown
show_downloads: false
github:
  is_project_page: true

plugins:
  - jekyll-sitemap